import { Event } from "./Event";
import { IMcApiPacket } from "./Network/McApiPackets/IMcApiPacket";
import { McApiAcceptResponsePacket } from "./Network/McApiPackets/Response/McApiAcceptResponsePacket";
import { McApiDenyResponsePacket } from "./Network/McApiPackets/Response/McApiDenyResponsePacket";
import { McApiPingResponsePacket } from "./Network/McApiPackets/Response/McApiPingResponsePacket";
import { McApiLoginRequestPacket } from "./Network/McApiPackets/Request/McApiLoginRequestPacket";
import { McApiPingRequestPacket } from "./Network/McApiPackets/Request/McApiPingRequestPacket";
import { McApiLogoutRequestPacket } from "./Network/McApiPackets/Request/McApiLogoutRequestPacket";
import { McApiOnEntityAudioReceivedPacket } from "./Network/McApiPackets/Event/McApiOnEntityAudioReceivedPacket";
import { McApiOnNetworkEntityCreatedPacket } from "./Network/McApiPackets/Event/McApiOnNetworkEntityCreatedPacket";
import { McApiOnEntityCreatedPacket } from "./Network/McApiPackets/Event/McApiOnEntityCreatedPacket";
import { McApiOnEntityDestroyedPacket } from "./Network/McApiPackets/Event/McApiOnEntityDestroyedPacket";
import { McApiSetEntityTitleRequestPacket } from "./Network/McApiPackets/Request/McApiSetEntityTitleRequestPacket";
import { McApiSetEntityDescriptionRequestPacket } from "./Network/McApiPackets/Request/McApiSetEntityDescriptionRequestPacket";
export declare class VoiceCraft {
    static readonly Namespace: string;
    private _writer;
    private _reader;
    private _connectionState;
    private _token?;
    constructor();
    get ConnectionState(): 0 | 1 | 2 | 3;
    get Token(): string | undefined;
    readonly OnPacket: Event<IMcApiPacket>;
    readonly OnLoginRequestPacket: Event<McApiLoginRequestPacket>;
    readonly OnLogoutRequestPacket: Event<McApiLogoutRequestPacket>;
    readonly OnPingRequestPacket: Event<McApiPingRequestPacket>;
    readonly OnSetEntityTitleRequestPacket: Event<McApiSetEntityTitleRequestPacket>;
    readonly OnSetEntityDescriptionRequestPacket: Event<McApiSetEntityDescriptionRequestPacket>;
    readonly OnAcceptResponsePacket: Event<McApiAcceptResponsePacket>;
    readonly OnDenyResponsePacket: Event<McApiDenyResponsePacket>;
    readonly OnPingResponsePacket: Event<McApiPingResponsePacket>;
    readonly OnEntityCreatedPacket: Event<McApiOnEntityCreatedPacket>;
    readonly OnNetworkEntityCreatedPacket: Event<McApiOnNetworkEntityCreatedPacket>;
    readonly OnEntityDestroyedPacket: Event<McApiOnEntityDestroyedPacket>;
    readonly OnEntityAudioReceivedPacket: Event<McApiOnEntityAudioReceivedPacket>;
    SendPacket(packet: IMcApiPacket): void;
    private HandleScriptEventAsync;
    private HandleOnPacketEventAsync;
    private HandleOnConnectedEvent;
    private HandleOnDisconnectedEvent;
    private HandlePacketAsync;
    private HandleLoginRequestPacket;
    private HandleLogoutRequestPacket;
    private HandlePingRequestPacket;
    private HandleSetEntityTitleRequestPacket;
    private HandleSetEntityDescriptionRequestPacket;
    private HandleAcceptResponsePacket;
    private HandleDenyResponsePacket;
    private HandlePingResponsePacket;
    private HandleOnEntityCreatedPacket;
    private HandleOnNetworkEntityCreatedPacket;
    private HandleOnEntityDestroyedPacket;
    private HandleOnEntityAudioReceivedPacket;
}
