import { Event } from "./API/Event";
import { Queue } from "./API/Data/Queue";
import "./Extensions";
import { IMcApiPacket } from "./API/Network/McApiPackets/IMcApiPacket";
export declare class McApiMcwss {
    private _version;
    private _commands;
    private _defaultTimeoutMs;
    private _token?;
    private _pinger?;
    private _writer;
    private _reader;
    private _lastPing;
    private _connectionState;
    private _requestIds;
    OutboundQueue: Queue<Uint8Array>;
    OnPacket: Event<IMcApiPacket>;
    ConnectAsync(token: string): Promise<void>;
    Disconnect(reason?: string): void;
    SendPacket(packet: IMcApiPacket): void;
    ReceivePacketAsync(packet: string): Promise<void>;
    private RegisterRequestId;
    private DeregisterRequestId;
    private GetResponseAsync;
    private PingIntervalLogic;
    private HandlePacketAsync;
    private HandleAcceptResponsePacket;
    private HandleDenyResponsePacket;
    private HandlePingResponsePacket;
}
