import { Event } from "./API/Event";
import { Queue } from "./API/Data/Queue";
import "./Extensions";
import { IMcApiPacket } from "./API/Network/McApiPackets/IMcApiPacket";
export declare class McApiMcHttp {
    private _version;
    private _cm;
    private _defaultTimeoutMs;
    private _hostname?;
    private _token?;
    private _pinger?;
    private _updater?;
    private _writer;
    private _reader;
    private _lastPing;
    private _connectionState;
    private _requestIds;
    OutboundQueue: Queue<Uint8Array>;
    OnPacket: Event<IMcApiPacket>;
    constructor();
    private HandleScriptEventAsync;
    private HandleSendPacketEventAsync;
    ConnectAsync(hostname: string, token: string): Promise<void>;
    Disconnect(reason?: string): void;
    SendPacket(packet: IMcApiPacket): void;
    ReceivePacketAsync(packet: string): Promise<void>;
    private StartHttpUpdater;
    private StartPinger;
    private StopHttpUpdater;
    private StopPinger;
    private RegisterRequestId;
    private DeregisterRequestId;
    private GetResponseAsync;
    private PingIntervalLogic;
    private HttpUpdaterLogic;
    private HandlePacketAsync;
    private HandleAcceptResponsePacket;
    private HandleDenyResponsePacket;
    private HandlePingResponsePacket;
}
