import { Event } from "./Event";
import { IMcApiPacket } from "./Network/McApiPackets/IMcApiPacket";
import { McApiAcceptResponsePacket } from "./Network/McApiPackets/Response/McApiAcceptResponsePacket";
import { McApiDenyResponsePacket } from "./Network/McApiPackets/Response/McApiDenyResponsePacket";
import { McApiPingResponsePacket } from "./Network/McApiPackets/Response/McApiPingResponsePacket";
import { McApiLoginRequestPacket } from "./Network/McApiPackets/Request/McApiLoginRequestPacket";
import { McApiPingRequestPacket } from "./Network/McApiPackets/Request/McApiPingRequestPacket";
import { McApiLogoutRequestPacket } from "./Network/McApiPackets/Request/McApiLogoutRequestPacket";
import { McApiOnEntityAudioReceivedPacket } from "./Network/McApiPackets/Event/McApiOnEntityAudioReceivedPacket";
import { McApiOnNetworkEntityCreatedPacket } from "./Network/McApiPackets/Event/McApiOnNetworkEntityCreatedPacket";
import { McApiOnEntityCreatedPacket } from "./Network/McApiPackets/Event/McApiOnEntityCreatedPacket";
import { McApiOnEntityDestroyedPacket } from "./Network/McApiPackets/Event/McApiOnEntityDestroyedPacket";
import { McApiSetEntityTitleRequestPacket } from "./Network/McApiPackets/Request/McApiSetEntityTitleRequestPacket";
import { McApiSetEntityDescriptionRequestPacket } from "./Network/McApiPackets/Request/McApiSetEntityDescriptionRequestPacket";
import { McApiOnEntityVisibilityUpdatedPacket } from "./Network/McApiPackets/Event/McApiOnEntityVisibilityUpdated";
import { McApiOnEntityWorldIdUpdatedPacket } from "./Network/McApiPackets/Event/McApiOnEntityWorldIdUpdated";
import { McApiOnEntityNameUpdatedPacket } from "./Network/McApiPackets/Event/McApiOnEntityNameUpdated";
import { McApiOnEntityMuteUpdatedPacket } from "./Network/McApiPackets/Event/McApiOnEntityMuteUpdated";
import { McApiOnEntityDeafenUpdatedPacket } from "./Network/McApiPackets/Event/McApiOnEntityDeafenUpdated";
import { McApiOnEntityTalkBitmaskUpdatedPacket } from "./Network/McApiPackets/Event/McApiOnEntityTalkBitmaskUpdated";
import { McApiOnEntityListenBitmaskUpdatedPacket } from "./Network/McApiPackets/Event/McApiOnEntityListenBitmaskUpdated";
import { McApiOnEntityEffectBitmaskUpdatedPacket } from "./Network/McApiPackets/Event/McApiOnEntityEffectBitmaskUpdated";
import { McApiOnEntityPositionUpdatedPacket } from "./Network/McApiPackets/Event/McApiOnEntityPositionUpdated";
import { McApiOnEntityRotationUpdatedPacket } from "./Network/McApiPackets/Event/McApiOnEntityRotationUpdated";
import { McApiOnEntityCaveFactorUpdatedPacket } from "./Network/McApiPackets/Event/McApiOnEntityCaveFactorUpdated";
import { McApiOnEntityMuffleFactorUpdatedPacket } from "./Network/McApiPackets/Event/McApiOnEntityMuffleFactorUpdated";
import { McApiSetEntityNameRequestPacket } from "./Network/McApiPackets/Request/McApiSetEntityNameRequestPacket";
import { McApiSetEntityTalkBitmaskRequestPacket } from "./Network/McApiPackets/Request/McApiSetEntityTalkBitmaskRequestPacket";
import { McApiSetEntityListenBitmaskRequestPacket } from "./Network/McApiPackets/Request/McApiSetEntityListenBitmaskRequestPacket";
import { McApiSetEntityEffectBitmaskRequestPacket } from "./Network/McApiPackets/Request/McApiSetEntityEffectBitmaskRequestPacket";
import { McApiSetEntityPositionRequestPacket } from "./Network/McApiPackets/Request/McApiSetEntityPositionRequestPacket";
import { McApiSetEntityRotationRequestPacket } from "./Network/McApiPackets/Request/McApiSetEntityRotationRequestPacket";
import { McApiSetEntityCaveFactorRequestPacket } from "./Network/McApiPackets/Request/McApiSetEntityCaveFactorRequestPacket";
import { McApiSetEntityMuffleFactorRequestPacket } from "./Network/McApiPackets/Request/McApiSetEntityMuffleFactorRequestPacket";
import { McApiSetEntityWorldIdRequestPacket } from "./Network/McApiPackets/Request/McApiSetEntityWorldIdRequestPacket";
import { McApiOnEffectUpdatedPacket } from "./Network/McApiPackets/Event/McApiOnEffectUpdatedPacket";
import { McApiSetEffectRequestPacket } from "./Network/McApiPackets/Request/McApiSetEffectRequestPacket";
import { McApiClearEffectsRequestPacket } from "./Network/McApiPackets/Request/McApiClearEffectsRequestPacket";
export declare class VoiceCraft {
    static readonly MajorVersion: number;
    static readonly MinorVersion: number;
    static readonly Namespace: string;
    private _writer;
    private _reader;
    private _connectionState;
    private _token?;
    constructor();
    get ConnectionState(): 0 | 1 | 2 | 3;
    get Token(): string | undefined;
    readonly OnConnected: Event<string>;
    readonly OnDisconnected: Event<string>;
    readonly OnPacket: Event<IMcApiPacket>;
    readonly OnLoginRequestPacket: Event<McApiLoginRequestPacket>;
    readonly OnLogoutRequestPacket: Event<McApiLogoutRequestPacket>;
    readonly OnPingRequestPacket: Event<McApiPingRequestPacket>;
    readonly OnAcceptResponsePacket: Event<McApiAcceptResponsePacket>;
    readonly OnDenyResponsePacket: Event<McApiDenyResponsePacket>;
    readonly OnPingResponsePacket: Event<McApiPingResponsePacket>;
    readonly OnSetEffectRequestPacket: Event<McApiSetEffectRequestPacket>;
    readonly OnClearEffectsRequestPacket: Event<McApiClearEffectsRequestPacket>;
    readonly OnSetEntityTitleRequestPacket: Event<McApiSetEntityTitleRequestPacket>;
    readonly OnSetEntityDescriptionRequestPacket: Event<McApiSetEntityDescriptionRequestPacket>;
    readonly OnSetEntityWorldIdRequestPacket: Event<McApiSetEntityWorldIdRequestPacket>;
    readonly OnSetEntityNameRequestPacket: Event<McApiSetEntityNameRequestPacket>;
    readonly OnSetEntityTalkBitmaskRequestPacket: Event<McApiSetEntityTalkBitmaskRequestPacket>;
    readonly OnSetEntityListenBitmaskRequestPacket: Event<McApiSetEntityListenBitmaskRequestPacket>;
    readonly OnSetEntityEffectBitmaskRequestPacket: Event<McApiSetEntityEffectBitmaskRequestPacket>;
    readonly OnSetEntityPositionRequestPacket: Event<McApiSetEntityPositionRequestPacket>;
    readonly OnSetEntityRotationRequestPacket: Event<McApiSetEntityRotationRequestPacket>;
    readonly OnSetEntityCaveFactorRequestPacket: Event<McApiSetEntityCaveFactorRequestPacket>;
    readonly OnSetEntityMuffleFactorRequestPacket: Event<McApiSetEntityMuffleFactorRequestPacket>;
    readonly OnEffectUpdatedPacket: Event<McApiOnEffectUpdatedPacket>;
    readonly OnEntityCreatedPacket: Event<McApiOnEntityCreatedPacket>;
    readonly OnNetworkEntityCreatedPacket: Event<McApiOnNetworkEntityCreatedPacket>;
    readonly OnEntityDestroyedPacket: Event<McApiOnEntityDestroyedPacket>;
    readonly OnEntityVisibilityUpdatedPacket: Event<McApiOnEntityVisibilityUpdatedPacket>;
    readonly OnEntityWorldIdUpdatedPacket: Event<McApiOnEntityWorldIdUpdatedPacket>;
    readonly OnEntityNameUpdatedPacket: Event<McApiOnEntityNameUpdatedPacket>;
    readonly OnEntityMuteUpdatedPacket: Event<McApiOnEntityMuteUpdatedPacket>;
    readonly OnEntityDeafenUpdatedPacket: Event<McApiOnEntityDeafenUpdatedPacket>;
    readonly OnEntityTalkBitmaskUpdatedPacket: Event<McApiOnEntityTalkBitmaskUpdatedPacket>;
    readonly OnEntityListenBitmaskUpdatedPacket: Event<McApiOnEntityListenBitmaskUpdatedPacket>;
    readonly OnEntityEffectBitmaskUpdatedPacket: Event<McApiOnEntityEffectBitmaskUpdatedPacket>;
    readonly OnEntityPositionUpdatedPacket: Event<McApiOnEntityPositionUpdatedPacket>;
    readonly OnEntityRotationUpdatedPacket: Event<McApiOnEntityRotationUpdatedPacket>;
    readonly OnEntityCaveFactorUpdatedPacket: Event<McApiOnEntityCaveFactorUpdatedPacket>;
    readonly OnEntityMuffleFactorUpdatedPacket: Event<McApiOnEntityMuffleFactorUpdatedPacket>;
    readonly OnEntityAudioReceivedPacket: Event<McApiOnEntityAudioReceivedPacket>;
    SendPacket(packet: IMcApiPacket): void;
    private HandleScriptEventAsync;
    private HandleOnPacketEventAsync;
    private HandleOnConnectedEvent;
    private HandleOnDisconnectedEvent;
    private HandlePacketAsync;
    private HandleLoginRequestPacket;
    private HandleLogoutRequestPacket;
    private HandlePingRequestPacket;
    private HandleAcceptResponsePacket;
    private HandleDenyResponsePacket;
    private HandlePingResponsePacket;
    private HandleSetEffectRequestPacket;
    private HandleClearEffectsRequestPacket;
    private HandleSetEntityTitleRequestPacket;
    private HandleSetEntityDescriptionRequestPacket;
    private HandleSetEntityWorldIdRequestPacket;
    private HandleSetEntityNameRequestPacket;
    private HandleSetEntityTalkBitmaskRequestPacket;
    private HandleSetEntityListenBitmaskRequestPacket;
    private HandleSetEntityEffectBitmaskRequestPacket;
    private HandleSetEntityPositionRequestPacket;
    private HandleSetEntityRotationRequestPacket;
    private HandleSetEntityCaveFactorRequestPacket;
    private HandleSetEntityMuffleFactorRequestPacket;
    private HandleOnEffectUpdatedPacket;
    private HandleOnEntityCreatedPacket;
    private HandleOnNetworkEntityCreatedPacket;
    private HandleOnEntityDestroyedPacket;
    private HandleOnEntityVisibilityUpdatedPacket;
    private HandleOnEntityWorldIdUpdatedPacket;
    private HandleOnEntityNameUpdatedPacket;
    private HandleOnEntityMuteUpdatedPacket;
    private HandleOnEntityDeafenUpdatedPacket;
    private HandleOnEntityTalkBitmaskUpdatedPacket;
    private HandleOnEntityListenBitmaskUpdatedPacket;
    private HandleOnEntityEffectBitmaskUpdatedPacket;
    private HandleOnEntityPositionUpdatedPacket;
    private HandleOnEntityRotationUpdatedPacket;
    private HandleOnEntityCaveFactorUpdatedPacket;
    private HandleOnEntityMuffleFactorUpdatedPacket;
    private HandleOnEntityAudioReceivedPacket;
}
