import { Event } from "./Event";
import { IMcApiPacket } from "./Network/McApiPackets/IMcApiPacket";
import { McApiAcceptResponsePacket } from "./Network/McApiPackets/Response/McApiAcceptResponsePacket";
import { McApiDenyResponsePacket } from "./Network/McApiPackets/Response/McApiDenyResponsePacket";
import { McApiPingResponsePacket } from "./Network/McApiPackets/Response/McApiPingResponsePacket";
import { McApiLoginRequestPacket } from "./Network/McApiPackets/Request/McApiLoginRequestPacket";
import { McApiPingRequestPacket } from "./Network/McApiPackets/Request/McApiPingRequestPacket";
import { McApiLogoutRequestPacket } from "./Network/McApiPackets/Request/McApiLogoutRequestPacket";
import { McApiOnEntityAudioReceivedPacket } from "./Network/McApiPackets/Event/McApiOnEntityAudioReceivedPacket";
export declare class VoiceCraft {
    static readonly Namespace: string;
    private _writer;
    private _reader;
    constructor();
    readonly OnPacket: Event<IMcApiPacket>;
    readonly OnLoginRequestPacket: Event<McApiLoginRequestPacket>;
    readonly OnLogoutRequestPacket: Event<McApiLogoutRequestPacket>;
    readonly OnPingRequestPacket: Event<McApiPingRequestPacket>;
    readonly OnAcceptResponsePacket: Event<McApiAcceptResponsePacket>;
    readonly OnDenyResponsePacket: Event<McApiDenyResponsePacket>;
    readonly OnPingResponsePacket: Event<McApiPingResponsePacket>;
    readonly OnEntityAudioReceivedPacket: Event<McApiOnEntityAudioReceivedPacket>;
    private HandleScriptEventAsync;
    private HandleOnPacketEventAsync;
    private HandlePacketAsync;
    private HandleLoginRequestPacket;
    private HandleLogoutRequestPacket;
    private HandlePingRequestPacket;
    private HandleAcceptResponsePacket;
    private HandleDenyResponsePacket;
    private HandlePingResponsePacket;
    private HandleOnEntityAudioReceivedPacket;
}
