import { McApiConnectionState } from "./Data/Enums";
import { IMcApiPacket } from "./Network/McApiPackets/IMcApiPacket";
import { Event } from "./Event";
import { NetDataReader } from "./Data/NetDataReader";
import { Queue } from "./Data/Queue";
export declare abstract class McApiClient {
    private _connectionState;
    private _token;
    private _lastPing;
    OutboundQueue: Queue<Uint8Array>;
    InboundQueue: Queue<Uint8Array>;
    get Token(): string | undefined;
    protected set Token(value: string | undefined);
    protected get LastPing(): number;
    protected set LastPing(value: number);
    OnPacketReceived: Event<IMcApiPacket>;
    OnConnected: Event<string>;
    OnDisconnected: Event<string>;
    get ConnectionState(): McApiConnectionState;
    protected set ConnectionState(value: McApiConnectionState);
    abstract ConnectAsync(ip: string, port: number, loginToken: string): Promise<void>;
    abstract Update(): void;
    abstract DisconnectAsync(reason: string | undefined): Promise<void>;
    abstract SendPacket(packet: IMcApiPacket): boolean;
    protected ProcessPacket(reader: NetDataReader, onParsed: (packet: IMcApiPacket) => void): void;
    protected ExecutePacket(packet: IMcApiPacket): void;
    protected AuthorizePacket(packet: IMcApiPacket, token: string): boolean;
    private ProcessPacketType;
    private HandleDenyResponsePacket;
}
