import { McApiConnectionState, McApiPacketType } from "./Data/Enums";
import { IMcApiPacket } from "./Network/McApiPackets/IMcApiPacket";
import { Event } from "./Event";
import { NetDataReader } from "./Data/NetDataReader";
import { Queue } from "./Data/Queue";
import { IMcApiRIdPacket } from "./Network/McApiPackets/IMcApiRIdPacket";
export declare abstract class McApiClient {
    private _voicecraft;
    private _connectionState;
    private _token;
    private _lastPing;
    OutboundQueue: Queue<Uint8Array>;
    InboundQueue: Queue<Uint8Array>;
    protected constructor();
    get Token(): string | undefined;
    protected set Token(value: string | undefined);
    protected get LastPing(): number;
    protected set LastPing(value: number);
    OnConnected: Event<string>;
    OnDisconnected: Event<string>;
    OnPacketReceived: Event<IMcApiPacket>;
    get ConnectionState(): McApiConnectionState;
    protected set ConnectionState(value: McApiConnectionState);
    abstract ConnectAsync(ip: string, port: number, loginToken: string): Promise<void>;
    abstract Update(): void;
    abstract DisconnectAsync(reason: string | undefined, force: boolean): Promise<void>;
    abstract SendPacket(packet: IMcApiPacket): boolean;
    protected GetResponseAsync<TPacket extends IMcApiPacket & IMcApiRIdPacket, TResult>(packetType: McApiPacketType, requestId: string, selector: (packet: TPacket) => TResult, timeoutTicks: number, token?: AbortSignal): Promise<TResult>;
    protected AuthorizePacket(packet: IMcApiPacket, token: string): boolean;
    protected ProcessPacket(reader: NetDataReader, onParsed: (packet: IMcApiPacket) => void): void;
    protected ExecutePacket(packet: IMcApiPacket): void;
    private HandleAcceptResponsePacket;
    private HandleDenyResponsePacket;
}
